name: quiz_master
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  get: ^4.7.2
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.0
  intl: ^0.20.2
  lottie: ^2.6.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appLogo.png"  # path to your icon

flutter:
  uses-material-design: true

  assets:
    - assets/icons/bg.svg
    - assets/icons/clock.svg
    - assets/lottie/leaderboard_trophy.json
    - assets/lottie/particles.json
    - assets/lottie/Its_a_quiz.json
    - assets/lottie/playQuiz.json
    - assets/lottie/
    - assets/icons/

